# Generated by Django 4.1.7 on 2023-04-11 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_listed', models.DateField()),
                ('date_added_to_db', models.DateField(verbose_name=datetime.datetime(2023, 4, 11, 14, 23, 14, 328883))),
            ],
        ),
    ]
