# Generated by Django 4.1.7 on 2023-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_listing_city_listing_county_listing_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date_listed']},
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
