# Generated by Django 4.1.7 on 2023-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_listing_options_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['date_added_to_db'], name='home_listin_date_ad_b59083_idx'),
        ),
    ]
