# Generated by Django 4.1.7 on 2023-04-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_listing_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
