# Generated by Django 4.1.7 on 2023-12-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
