# Generated by Django 4.1.7 on 2023-12-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_listing_searches'),
        ('home', '0008_alter_urls_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLs',
            new_name='ReferenceURLs',
        ),
    ]
