# Generated by Django 4.1.7 on 2023-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_listing_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_images',
            field=models.IntegerField(default=0),
        ),
    ]
