# Generated by Django 4.1.7 on 2023-05-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_listing_num_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='liked',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=1)),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to='scraper.listing')),
            ],
        ),
    ]
