# Generated by Django 4.1.7 on 2023-06-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_listing_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
