# Generated by Django 4.1.7 on 2023-10-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_alter_listing_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedListings',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('page', models.IntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.listing')),
            ],
        ),
    ]
