# Generated by Django 4.1.7 on 2023-10-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_searchedlistings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedlistings',
            name='listing',
        ),
    ]
