# Generated by Django 4.1.7 on 2023-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_remove_searchedlistings_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedlistings',
            name='hashref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
