# Generated by Django 4.1.7 on 2023-12-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_urls_id'),
        ('scraper', '0015_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='searches',
            field=models.ManyToManyField(to='home.urls'),
        ),
    ]
