# Generated by Django 4.1.7 on 2023-12-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_listing_searches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='searches',
            new_name='referenceurls',
        ),
    ]
